### ISSUE TITLE
It looks like 

### ISSUE THREAD

**Issue by dlohin** [clearcontainers/sriov#6]
I was unable to find the package uuid.  It looks like CIAO moved uuid to its own parent.

plugin.go:34:2: cannot find package "github.com/01org/ciao/ssntp/uuid" in any of:
	/usr/lib/golang/src/github.com/01org/ciao/ssntp/uuid (from $GOROOT)
	/root/gocode/src/github.com/01org/ciao/ssntp/uuid (from $GOPATH)

To fix this, I changed it to import         "github.com/01org/ciao/uuid"

Then I was able to go get github.com/01org/ciao/uuid/

and it worked.

**Comment by mcastelino** [comment]
Fixed by https://github.com/clearcontainers/sriov/pull/8
